# Generated by Django 3.2.5 on 2021-07-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='available_display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
    ]
